# Generated by Django 4.2.10 on 2024-04-06 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenseplate', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('city', models.CharField(max_length=100)),
                ('images1', models.ImageField(upload_to='images/')),
                ('images2', models.ImageField(upload_to='images/')),
                ('images3', models.ImageField(upload_to='images/')),
                ('images4', models.ImageField(upload_to='images/')),
                ('images5', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('spotter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenseplate', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
