# Generated by Django 4.2.10 on 2024-04-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
