# Generated by Django 4.2.10 on 2024-04-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0002_rename_owner_posts_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='owner_id',
            field=models.IntegerField(default=0),
        ),
    ]
