# Generated by Django 4.2.10 on 2024-04-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0006_follows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follows',
            old_name='user_id',
            new_name='user',
        ),
    ]
