# Generated by Django 4.2.10 on 2024-04-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0009_thread_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepics',
            name='images',
            field=models.ImageField(upload_to='images/profilepics'),
        ),
    ]
