# Generated by Django 4.2.10 on 2024-04-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0014_rename_images_profilepics_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepics',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
